apiVersion: "tanzu.vmware.com/v1"
kind: SpringCloudGateway
metadata:
  name: gac-demo
  namespace: gac-demo
spec:
  api:
    serverUrl: https://gac-demo.dragonstone.tkg-aws-e2-lab.winterfell.be
    title: "Httpbin demo"
    description: "Sample application for Spring Cloud Gateway commercial product demos."
    documentation: "https://github.com/spring-cloud-services-samples/animal-rescue/"
    version: "1.0.0-K8s"
    cors:
      allowedOrigins:
      - "https://httpbin.org"
      - "https://api-portal.dragonstone.tkg-aws-e2-lab.winterfell.be"
  count: 1
  observability:
    metrics:
      prometheus:
        enabled:  true
        annotations:
          enabled: true

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gac-demo
  namespace: gac-demo
  labels:
    app: gac-demo
#  annotations:
#    ingress.kubernetes.io/force-ssl-redirect: "true"
#    kubernetes.io/ingress.class: contour
spec:
#  tls:
#  - secretName: gac-demo-cert-tls
#    hosts:
#    - "gac-demo.dragonstone.tkg-aws-e2-lab.winterfell.be"
  rules:
  - host: gac-demo.dragonstone.tkg-aws-e2-lab.winterfell.be
    http:
      paths:
      - backend:
          service:
            name: gac-demo
            port:
              number: 80
        pathType: ImplementationSpecific

