apiVersion: "tanzu.vmware.com/v1"
kind: SpringCloudGatewayRouteConfig
metadata:
  name: httpbin-uuid-route-config
spec:
  routes:
    - predicates:
        - Path=/api/demo
        - Host=**.winterfell.be
        - Method=GET
      uri: http://httpbin.org
      filters:
        - SetPath=/uuid
      tags:
        - api
      title: "To test scg to forward uuid request to httpbin/uuid"
      description: "httpbin endpoint uuid testcase"
    - predicates:
        - Path=/api/demo/{delay}
        - Host=**.winterfell.be
        - Method=GET
      uri: http://httpbin.org
      filters:
        - SetPath=/drip
       # duration=2&delay=1&code=200&numbytes=10
        - AddRequestParameter=duration, 0
        - AddRequestParameter=delay, {delay}
        - AddRequestParameter=code, 200
        - AddRequestParameter=numbytes, 10
        - CircuitBreaker=myCircuitBreaker, forward:/api/fallback
    - predicates:
        - Path=/api/fallback
      uri: http://httpbin.org
      filters:
        - SetPath=/uuid
        - FallbackHeaders
      tags:
        - fallback
      title: "To test scg to behave fallback if request to /demo/{delay} is failed"
      description: "httpbin endpoint uuid testcase for fallback"

